### ISSUE TITLE
Client allows you to enter text with keys other than the enter key.

### ISSUE THREAD

**Issue by derbiter** [willluongo/asbestos#5]
You can use all four arrow keys, the tab key, and the escape key to enter your text.

...But I still think this is the best feature.

**Comment by willluongo** [comment]
This is an issue with the way the gui handles traverse events. I'll get right to work on this, sir.

**Comment by derbiter** [comment]
Good. Good. You have proven your allegiance.

**Comment by willluongo** [comment]
Please close it after the release with the change.

**Comment by willluongo** [comment]
Fix released in v0.0.2-alpha
